# This is a basic workflow to help you get started with Actions

name: main

# Controls when the workflow will run
on:
  # Triggers the workflow on push to any branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  compile2:
    runs-on: ubuntu-latest
    container: openjdk

    steps:
      - uses: actions/checkout@v2
      - name: Compile Pacman Project and Tests
        working-directory: Projects/P1
        run: javac -cp "tests/junit-4.10.jar:." src/*.java tests/*.java  
